<a href="https://colab.research.google.com/github/avhishekz/Python/blob/main/8_April_(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NUMPY : library written in 'c' & 'Fortran' //Mathematical operations

In [3]:
import numpy as np


In [17]:
arr1=np.array([1,2,3,4,5])

In [18]:
type(arr1)

numpy.ndarray

In [19]:
#manual initilaize in 2d array
arr2=np.array([[1,2,3,4],[1,5,6,6]])

In [23]:

arr3 = np.zeros((4, 3))

In [24]:
arr45=np.identity(5)

In [35]:
arr9=([1,2,3,4,5])

In [26]:
arr9=np.linspace(10,20,10)   #lower and higher range     linearly spaced

In [36]:
arr10=arr9.copy()
arr10

[1, 2, 3, 4, 5]

In [28]:
arr1

array([1, 2, 3, 4, 5])

In [29]:
arr2.shape

(2, 4)

In [31]:
arr11 = np.array([[1, 2, 3], [4, 5, 6]])

In [33]:
arr11.ndim    #dimensions btata hai

2

In [34]:
arr1

array([1, 2, 3, 4, 5])

In [37]:
arr1.ndim    #Attribute hai ye not function

1

In [39]:
arr1.size

5

In [40]:
arr11.size

6

In [43]:
arr11.itemsize

8

In [44]:
arr12=np.array([1,6,7,5])

In [45]:
arr3.dtype

dtype('float64')

In [49]:
arr23 = arr3.astype("int")


In [51]:
arr23.itemsize

8

In [ ]:
#PYTHON LIST VS NUMPPY ARRAYS

In [ ]:
#Numpy array /faster
#less memory
#convinent

In [68]:
my_list = list(range(100))
Ary1 = np.arange(100)


In [69]:
print(Ary1.itemsize*arr1.size)

40


In [59]:
import sys

In [70]:
sys.getsizeof(9)

28

In [73]:
import time
x=range(1000)   #999 tk value lega
y=range(1000,2000)

start_time=time.time()   # isse pta chlega ki time kitna hai abhi  // stored here  // time saved at start time

c = [(a + b) for a, b in zip(x, y)]

print(time.time() - start_time)  #kitna time lga

0.0003502368927001953


In [76]:
import numpy as np
import time

a = np.arange(10000000)
b = np.arange(10000000, 20000000)

start_time = time.time()
c = a + b
print("Time taken:", time.time() - start_time)


Time taken: 0.11109375953674316


In [ ]:
#Indexing and slicing


In [94]:
import numpy as np

arr12 = np.arange(24)
print(arr12)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [84]:
arr12 = arr12.reshape((6, 4))
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [89]:
arr13 = np.array([1, 2, 3, 4, 5])
arr13


array([1, 2, 3, 4, 5])

In [90]:
arr13[3]

4

In [91]:
arr13[2:3]

array([3])

In [92]:
arr13[2:4]

array([3, 4])

In [95]:
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [97]:
arr14=arr12.reshape(6,4)
arr14

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [101]:
arr14[2]

array([ 8,  9, 10, 11])

In [103]:
arr14[:2]  #sare till 2nd row

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [104]:
arr14[2:]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [105]:
arr14[:,2]   #column ka value

array([ 2,  6, 10, 14, 18, 22])

In [106]:
arr14[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [109]:
arr14[4:,2:]

array([[18, 19],
       [22, 23]])